apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
        - name: cloudapp
          image: sadik789diwan/cloudapp:latest
          ports:
            - containerPort: 8080