apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
        - name: cloudapp
          image: sadik789diwan/cloudapp:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          # 🔐 Inject Secret here
          envFrom:
            - secretRef:
                name: cloudapp-secret

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10