spring.application.name=cloudapp
server.port=8080

#app.custom-message=Hello from the Properties File!
#app.status-code=200

app.custom-message=${APP_CUSTOM_MESSAGE:default-message}
app.status-code=${APP_STATUS_CODE:200}