name: Spring Boot CI (Maven + Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sadik789diwan/cloudapp
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ github.run_number }}
